### ISSUE TITLE
Unsubsccribe in WidgetHost.xaml.cs

### ISSUE THREAD

**Issue by rubend30** [DustinBryant/WpfDashboardControl#3]
Hello

Is it possible that in the `WidgetHost` class the `WidgetHost_Unloaded` should unsubscribe the `PreviewMouseLeftButtonDown` and `PreviewMouseMove` instead of subscribing?

Now it is like this:
```
private void WidgetHost_Loaded(object sender, RoutedEventArgs e)
{
    Loaded -= WidgetHost_Loaded;

    PreviewMouseLeftButtonDown += Host_MouseLeftButtonDown;
    PreviewMouseMove += Host_MouseMove;
}

private void WidgetHost_Unloaded(object sender, RoutedEventArgs e)
{
    Unloaded -= WidgetHost_Unloaded;

    PreviewMouseLeftButtonDown += Host_MouseLeftButtonDown;
    PreviewMouseMove += Host_MouseMove;
}
```

Is this by design or a small bug?

Kind regards

**Comment by DustinBryant** [comment]
@rubend30 this is a bug. Thanks for pointing it out for me. I've updated the master branch with commit 31f8d61.
